In [42]:
!pip3 install prometheus_api_client pandas matplotlib

Requirement already satisfied: prometheus_api_client in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (0.7.0)
Requirement already satisfied: pandas in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: matplotlib in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (3.10.8)
Requirement already satisfied: requests in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from prometheus_api_client) (2.32.5)
Requirement already satisfied: dateparser in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from prometheus_api_client) (1.3.0)
Requirement already satisfied: numpy>=1.26.0 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: pytz>=2024.2 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from dateparser->prometheus_api_client) (2026.1.post1)
Requirement already satisfied: regex>=2024.9.11 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from dateparser->prometheus_api_client) (2026.2.28)
Requirement already satisfied: tzlocal>=0.2 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from dateparser->prometheus_api_client) (5.3.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from requests->prometheus_api_client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from requests->prometheus_api_client) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from requests->prometheus_api_client) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/testuser/PREDICTIVE-K8S-CA/venv/lib/python3.12/site-packages (from requests->prometheus_api_client) (2026.2.25)

In [43]:
# Query Data
from prometheus_api_client import PrometheusConnect, MetricRangeDataFrame
from datetime import datetime
import pandas as pd
import zoneinfo

# Connect to Prometheus
prom = PrometheusConnect(url = "http://10.35.29.108:31102", disable_ssl = True)

# Define Time Range
thai_tz = zoneinfo.ZoneInfo("Asia/Bangkok")

# Create datetime objects localized to Thai time
start_time_thai = datetime(2026, 2, 28, 14, 0, 0, tzinfo = thai_tz)
end_time_thai = datetime(2026, 3, 3, 14, 0, 0, tzinfo = thai_tz)

print(f"Fetching data from {start_time_thai} to {end_time_thai}...")
print(int(start_time_thai.timestamp()))
print(int(end_time_thai.timestamp()))

Fetching data from 2026-02-28 14:00:00+07:00 to 2026-03-03 14:00:00+07:00...
1772262000
1772521200

In [44]:
print(prom.all_metrics())

[':node_memory_MemAvailable_bytes:sum', 'ALERTS', 'ALERTS_FOR_STATE', 'aggregator_discovery_aggregation_count_total', 'aggregator_unavailable_apiservice', 'aggregator_unavailable_apiservice_total', 'alertmanager_alerts', 'alertmanager_alerts_invalid_total', 'alertmanager_alerts_received_total', 'alertmanager_alerts_subscriber_channel_writes_total', 'alertmanager_build_info', 'alertmanager_cluster_enabled', 'alertmanager_config_hash', 'alertmanager_config_last_reload_success_timestamp_seconds', 'alertmanager_config_last_reload_successful', 'alertmanager_dispatcher_aggregation_group_limit_reached_total', 'alertmanager_dispatcher_aggregation_groups', 'alertmanager_dispatcher_alert_processing_duration_seconds_count', 'alertmanager_dispatcher_alert_processing_duration_seconds_sum', 'alertmanager_http_concurrency_limit_exceeded_total', 'alertmanager_http_request_duration_seconds_bucket', 'alertmanager_http_request_duration_seconds_count', 'alertmanager_http_request_duration_seconds_sum', 'alertmanager_http_requests_in_flight', 'alertmanager_http_response_size_bytes_bucket', 'alertmanager_http_response_size_bytes_count', 'alertmanager_http_response_size_bytes_sum', 'alertmanager_inhibition_rules', 'alertmanager_integrations', 'alertmanager_marked_alerts', 'alertmanager_nflog_gc_duration_seconds_count', 'alertmanager_nflog_gc_duration_seconds_sum', 'alertmanager_nflog_gossip_messages_propagated_total', 'alertmanager_nflog_maintenance_errors_total', 'alertmanager_nflog_maintenance_total', 'alertmanager_nflog_queries_total', 'alertmanager_nflog_query_duration_seconds_bucket', 'alertmanager_nflog_query_duration_seconds_count', 'alertmanager_nflog_query_duration_seconds_sum', 'alertmanager_nflog_query_errors_total', 'alertmanager_nflog_snapshot_duration_seconds_count', 'alertmanager_nflog_snapshot_duration_seconds_sum', 'alertmanager_nflog_snapshot_size_bytes', 'alertmanager_notification_latency_seconds_bucket', 'alertmanager_notification_latency_seconds_count', 'alertmanager_notification_latency_seconds_sum', 'alertmanager_notification_requests_failed_total', 'alertmanager_notification_requests_total', 'alertmanager_notifications_failed_total', 'alertmanager_notifications_suppressed_total', 'alertmanager_notifications_total', 'alertmanager_receivers', 'alertmanager_silences_gc_duration_seconds_count', 'alertmanager_silences_gc_duration_seconds_sum', 'alertmanager_silences_gc_errors_total', 'alertmanager_silences_gossip_messages_propagated_total', 'alertmanager_silences_maintenance_errors_total', 'alertmanager_silences_maintenance_total', 'alertmanager_silences_matcher_compile_errors_total', 'alertmanager_silences_matcher_index_size', 'alertmanager_silences_queries_total', 'alertmanager_silences_query_duration_seconds_bucket', 'alertmanager_silences_query_duration_seconds_count', 'alertmanager_silences_query_duration_seconds_sum', 'alertmanager_silences_query_errors_total', 'alertmanager_silences_query_silences_scanned_total', 'alertmanager_silences_query_silences_skipped_total', 'alertmanager_silences_snapshot_duration_seconds_count', 'alertmanager_silences_snapshot_duration_seconds_sum', 'alertmanager_silences_snapshot_size_bytes', 'alertmanager_silences_state_size', 'alertmanager_silences_version_index_size', 'apiextensions_apiserver_validation_ratcheting_seconds_bucket', 'apiextensions_apiserver_validation_ratcheting_seconds_count', 'apiextensions_apiserver_validation_ratcheting_seconds_sum', 'apiextensions_openapi_v2_regeneration_count', 'apiextensions_openapi_v3_regeneration_count', 'apiserver_admission_controller_admission_duration_seconds_bucket', 'apiserver_admission_controller_admission_duration_seconds_count', 'apiserver_admission_controller_admission_duration_seconds_sum', 'apiserver_admission_step_admission_duration_seconds_bucket', 'apiserver_admission_step_admission_duration_seconds_count', 'apiserver_admission_step_admission_duration_seconds_sum', 'apiserver_admission_step_admission_duration_seconds_summary', 'apiserver_admission_step_admission_duration_seconds_summary_count', 'apiserver_admission_step_admission_duration_seconds_summary_sum', 'apiserver_audit_event_total', 'apiserver_audit_requests_rejected_total', 'apiserver_authorization_decisions_total', 'apiserver_cache_list_fetched_objects_total', 'apiserver_cache_list_returned_objects_total', 'apiserver_cache_list_total', 'apiserver_cel_compilation_duration_seconds_bucket', 'apiserver_cel_compilation_duration_seconds_count', 'apiserver_cel_compilation_duration_seconds_sum', 'apiserver_cel_evaluation_duration_seconds_bucket', 'apiserver_cel_evaluation_duration_seconds_count', 'apiserver_cel_evaluation_duration_seconds_sum', 'apiserver_client_certificate_expiration_seconds_bucket', 'apiserver_client_certificate_expiration_seconds_count', 'apiserver_client_certificate_expiration_seconds_sum', 'apiserver_current_inflight_requests', 'apiserver_current_inqueue_requests', 'apiserver_delegated_authn_request_duration_seconds_bucket', 'apiserver_delegated_authn_request_duration_seconds_count', 'apiserver_delegated_authn_request_duration_seconds_sum', 'apiserver_delegated_authn_request_total', 'apiserver_delegated_authz_request_duration_seconds_bucket', 'apiserver_delegated_authz_request_duration_seconds_count', 'apiserver_delegated_authz_request_duration_seconds_sum', 'apiserver_delegated_authz_request_total', 'apiserver_envelope_encryption_dek_cache_fill_percent', 'apiserver_flowcontrol_current_executing_requests', 'apiserver_flowcontrol_current_executing_seats', 'apiserver_flowcontrol_current_inqueue_requests', 'apiserver_flowcontrol_current_inqueue_seats', 'apiserver_flowcontrol_current_limit_seats', 'apiserver_flowcontrol_current_r', 'apiserver_flowcontrol_demand_seats_average', 'apiserver_flowcontrol_demand_seats_bucket', 'apiserver_flowcontrol_demand_seats_count', 'apiserver_flowcontrol_demand_seats_high_watermark', 'apiserver_flowcontrol_demand_seats_smoothed', 'apiserver_flowcontrol_demand_seats_stdev', 'apiserver_flowcontrol_demand_seats_sum', 'apiserver_flowcontrol_dispatch_r', 'apiserver_flowcontrol_dispatched_requests_total', 'apiserver_flowcontrol_latest_s', 'apiserver_flowcontrol_lower_limit_seats', 'apiserver_flowcontrol_next_discounted_s_bounds', 'apiserver_flowcontrol_next_s_bounds', 'apiserver_flowcontrol_nominal_limit_seats', 'apiserver_flowcontrol_priority_level_request_utilization_bucket', 'apiserver_flowcontrol_priority_level_request_utilization_count', 'apiserver_flowcontrol_priority_level_request_utilization_sum', 'apiserver_flowcontrol_priority_level_seat_utilization_bucket', 'apiserver_flowcontrol_priority_level_seat_utilization_count', 'apiserver_flowcontrol_priority_level_seat_utilization_sum', 'apiserver_flowcontrol_read_vs_write_current_requests_bucket', 'apiserver_flowcontrol_read_vs_write_current_requests_count', 'apiserver_flowcontrol_read_vs_write_current_requests_sum', 'apiserver_flowcontrol_request_execution_seconds_bucket', 'apiserver_flowcontrol_request_execution_seconds_count', 'apiserver_flowcontrol_request_execution_seconds_sum', 'apiserver_flowcontrol_request_queue_length_after_enqueue_bucket', 'apiserver_flowcontrol_request_queue_length_after_enqueue_count', 'apiserver_flowcontrol_request_queue_length_after_enqueue_sum', 'apiserver_flowcontrol_request_wait_duration_seconds_bucket', 'apiserver_flowcontrol_request_wait_duration_seconds_count', 'apiserver_flowcontrol_request_wait_duration_seconds_sum', 'apiserver_flowcontrol_seat_fair_frac', 'apiserver_flowcontrol_target_seats', 'apiserver_flowcontrol_upper_limit_seats', 'apiserver_flowcontrol_watch_count_samples_bucket', 'apiserver_flowcontrol_watch_count_samples_count', 'apiserver_flowcontrol_watch_count_samples_sum', 'apiserver_flowcontrol_work_estimated_seats_bucket', 'apiserver_flowcontrol_work_estimated_seats_count', 'apiserver_flowcontrol_work_estimated_seats_sum', 'apiserver_init_events_total', 'apiserver_kube_aggregator_x509_insecure_sha1_total', 'apiserver_kube_aggregator_x509_missing_san_total', 'apiserver_longrunning_requests', 'apiserver_nodeport_repair_reconcile_errors_total', 'apiserver_request:availability30d', 'apiserver_request:burnrate1d', 'apiserver_request:burnrate1h', 'apiserver_request:burnrate2h', 'apiserver_request:burnrate30m', 'apiserver_request:burnrate3d', 'apiserver_request:burnrate5m', 'apiserver_request:burnrate6h', 'apiserver_request_aborts_total', 'apiserver_request_body_size_bytes_bucket', 'apiserver_request_body_size_bytes_count', 'apiserver_request_body_size_bytes_sum', 'apiserver_request_duration_seconds_bucket', 'apiserver_request_duration_seconds_count', 'apiserver_request_duration_seconds_sum', 'apiserver_request_filter_duration_seconds_bucket', 'apiserver_request_filter_duration_seconds_count', 'apiserver_request_filter_duration_seconds_sum', 'apiserver_request_post_timeout_total', 'apiserver_request_sli_duration_seconds_bucket', 'apiserver_request_sli_duration_seconds_count', 'apiserver_request_sli_duration_seconds_sum', 'apiserver_request_terminations_total', 'apiserver_request_timestamp_comparison_time_bucket', 'apiserver_request_timestamp_comparison_time_count', 'apiserver_request_timestamp_comparison_time_sum', 'apiserver_request_total', 'apiserver_requested_deprecated_apis', 'apiserver_resource_objects', 'apiserver_resource_size_estimate_bytes', 'apiserver_response_sizes_bucket', 'apiserver_response_sizes_count', 'apiserver_response_sizes_sum', 'apiserver_selfrequest_total', 'apiserver_storage_consistency_checks_total', 'apiserver_storage_data_key_generation_duration_seconds_bucket', 'apiserver_storage_data_key_generation_duration_seconds_count', 'apiserver_storage_data_key_generation_duration_seconds_sum', 'apiserver_storage_data_key_generation_failures_total', 'apiserver_storage_envelope_transformation_cache_misses_total', 'apiserver_storage_events_received_total', 'apiserver_storage_list_evaluated_objects_total', 'apiserver_storage_list_fetched_objects_total', 'apiserver_storage_list_returned_objects_total', 'apiserver_storage_list_total', 'apiserver_storage_objects', 'apiserver_storage_size_bytes', 'apiserver_tls_handshake_errors_total', 'apiserver_validation_declarative_validation_mismatch_total', 'apiserver_validation_declarative_validation_panic_total', 'apiserver_watch_cache_consistent_read_total', 'apiserver_watch_cache_events_dispatched_total', 'apiserver_watch_cache_events_received_total', 'apiserver_watch_cache_initializations_total', 'apiserver_watch_cache_read_wait_seconds_bucket', 'apiserver_watch_cache_read_wait_seconds_count', 'apiserver_watch_cache_read_wait_seconds_sum', 'apiserver_watch_cache_resource_version', 'apiserver_watch_events_sizes_bucket', 'apiserver_watch_events_sizes_count', 'apiserver_watch_events_sizes_sum', 'apiserver_watch_events_total', 'apiserver_watch_list_duration_seconds_bucket', 'apiserver_watch_list_duration_seconds_count', 'apiserver_watch_list_duration_seconds_sum', 'apiserver_webhooks_x509_insecure_sha1_total', 'apiserver_webhooks_x509_missing_san_total', 'authenticated_user_requests', 'authentication_attempts', 'authentication_duration_seconds_bucket', 'authentication_duration_seconds_count', 'authentication_duration_seconds_sum', 'authentication_token_cache_active_fetch_count', 'authentication_token_cache_fetch_total', 'authentication_token_cache_request_duration_seconds_bucket', 'authentication_token_cache_request_duration_seconds_count', 'authentication_token_cache_request_duration_seconds_sum', 'authentication_token_cache_request_total', 'authorization_attempts_total', 'authorization_duration_seconds_bucket', 'authorization_duration_seconds_count', 'authorization_duration_seconds_sum', 'cadvisor_version_info', 'cardinality_enforcement_unexpected_categorizations_total', 'cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits', 'cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests', 'cluster:namespace:pod_memory:active:kube_pod_container_resource_limits', 'cluster:namespace:pod_memory:active:kube_pod_container_resource_requests', 'cluster:node_cpu:ratio', 'cluster:node_cpu:ratio_rate5m', 'cluster:node_cpu:sum_rate5m', 'cluster_quantile:apiserver_request_sli_duration_seconds:histogram_quantile', 'cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase1h', 'cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d', 'cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase1h', 'cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d', 'code:apiserver_request_total:increase30d', 'code_resource:apiserver_request_total:rate5m', 'code_verb:apiserver_request_total:increase1h', 'code_verb:apiserver_request_total:increase30d', 'container_blkio_device_usage_total', 'container_cpu_cfs_periods_total', 'container_cpu_cfs_throttled_periods_total', 'container_cpu_load_d_average_10s', 'container_cpu_usage_seconds_total', 'container_fs_reads_bytes_total', 'container_fs_reads_total', 'container_fs_writes_bytes_total', 'container_fs_writes_total', 'container_last_seen', 'container_memory_cache', 'container_memory_failcnt', 'container_memory_failures_total', 'container_memory_kernel_usage', 'container_memory_max_usage_bytes', 'container_memory_rss', 'container_memory_total_active_file_bytes', 'container_memory_total_inactive_file_bytes', 'container_memory_usage_bytes', 'container_memory_working_set_bytes', 'container_network_receive_bytes_total', 'container_network_receive_errors_total', 'container_network_receive_packets_dropped_total', 'container_network_receive_packets_total', 'container_network_transmit_bytes_total', 'container_network_transmit_errors_total', 'container_network_transmit_packets_dropped_total', 'container_network_transmit_packets_total', 'container_oom_events_total', 'container_pressure_cpu_stalled_seconds_total', 'container_pressure_cpu_waiting_seconds_total', 'container_pressure_io_stalled_seconds_total', 'container_pressure_io_waiting_seconds_total', 'container_pressure_memory_stalled_seconds_total', 'container_pressure_memory_waiting_seconds_total', 'container_processes', 'container_scrape_error', 'container_sockets', 'container_start_time_seconds', 'container_threads', 'container_ulimits_soft', 'coredns_build_info', 'coredns_cache_entries', 'coredns_cache_hits_total', 'coredns_cache_misses_total', 'coredns_cache_requests_total', 'coredns_dns_request_duration_seconds_bucket', 'coredns_dns_request_duration_seconds_count', 'coredns_dns_request_duration_seconds_sum', 'coredns_dns_request_size_bytes_bucket', 'coredns_dns_request_size_bytes_count', 'coredns_dns_request_size_bytes_sum', 'coredns_dns_requests_total', 'coredns_dns_response_size_bytes_bucket', 'coredns_dns_response_size_bytes_count', 'coredns_dns_response_size_bytes_sum', 'coredns_dns_responses_total', 'coredns_forward_healthcheck_broken_total', 'coredns_forward_max_concurrent_rejects_total', 'coredns_health_request_duration_seconds_bucket', 'coredns_health_request_duration_seconds_count', 'coredns_health_request_duration_seconds_sum', 'coredns_health_request_failures_total', 'coredns_hosts_reload_timestamp_seconds', 'coredns_kubernetes_dns_programming_duration_seconds_bucket', 'coredns_kubernetes_dns_programming_duration_seconds_count', 'coredns_kubernetes_dns_programming_duration_seconds_sum', 'coredns_kubernetes_rest_client_rate_limiter_duration_seconds_bucket', 'coredns_kubernetes_rest_client_rate_limiter_duration_seconds_count', 'coredns_kubernetes_rest_client_rate_limiter_duration_seconds_sum', 'coredns_kubernetes_rest_client_request_duration_seconds_bucket', 'coredns_kubernetes_rest_client_request_duration_seconds_count', 'coredns_kubernetes_rest_client_request_duration_seconds_sum', 'coredns_kubernetes_rest_client_requests_total', 'coredns_local_localhost_requests_total', 'coredns_panics_total', 'coredns_plugin_enabled', 'coredns_proxy_conn_cache_hits_total', 'coredns_proxy_conn_cache_misses_total', 'coredns_proxy_healthcheck_failures_total', 'coredns_proxy_request_duration_seconds_bucket', 'coredns_proxy_request_duration_seconds_count', 'coredns_proxy_request_duration_seconds_sum', 'coredns_reload_failed_total', 'count:up0', 'count:up1', 'deprecated_flags_inuse_total', 'disabled_metrics_total', 'dra_operations_duration_seconds_bucket', 'dra_operations_duration_seconds_count', 'dra_operations_duration_seconds_sum', 'dra_resource_claims_in_use', 'etcd_bookmark_counts', 'etcd_lease_object_counts_bucket', 'etcd_lease_object_counts_count', 'etcd_lease_object_counts_sum', 'etcd_request_duration_seconds_bucket', 'etcd_request_duration_seconds_count', 'etcd_request_duration_seconds_sum', 'etcd_request_errors_total', 'etcd_requests_total', 'field_validation_request_duration_seconds_bucket', 'field_validation_request_duration_seconds_count', 'field_validation_request_duration_seconds_sum', 'force_cleaned_failed_volume_operation_errors_total', 'force_cleaned_failed_volume_operations_total', 'go_cgo_go_to_c_calls_calls_total', 'go_cpu_classes_gc_mark_assist_cpu_seconds_total', 'go_cpu_classes_gc_mark_dedicated_cpu_seconds_total', 'go_cpu_classes_gc_mark_idle_cpu_seconds_total', 'go_cpu_classes_gc_pause_cpu_seconds_total', 'go_cpu_classes_gc_total_cpu_seconds_total', 'go_cpu_classes_idle_cpu_seconds_total', 'go_cpu_classes_scavenge_assist_cpu_seconds_total', 'go_cpu_classes_scavenge_background_cpu_seconds_total', 'go_cpu_classes_scavenge_total_cpu_seconds_total', 'go_cpu_classes_total_cpu_seconds_total', 'go_cpu_classes_user_cpu_seconds_total', 'go_gc_cycles_automatic_gc_cycles_total', 'go_gc_cycles_forced_gc_cycles_total', 'go_gc_cycles_total_gc_cycles_total', 'go_gc_duration_seconds', 'go_gc_duration_seconds_count', 'go_gc_duration_seconds_sum', 'go_gc_gogc_percent', 'go_gc_gomemlimit_bytes', 'go_gc_heap_allocs_by_size_bytes_bucket', 'go_gc_heap_allocs_by_size_bytes_count', 'go_gc_heap_allocs_by_size_bytes_sum', 'go_gc_heap_allocs_bytes_total', 'go_gc_heap_allocs_objects_total', 'go_gc_heap_frees_by_size_bytes_bucket', 'go_gc_heap_frees_by_size_bytes_count', 'go_gc_heap_frees_by_size_bytes_sum', 'go_gc_heap_frees_bytes_total', 'go_gc_heap_frees_objects_total', 'go_gc_heap_goal_bytes', 'go_gc_heap_live_bytes', 'go_gc_heap_objects_objects', 'go_gc_heap_tiny_allocs_objects_total', 'go_gc_limiter_last_enabled_gc_cycle', 'go_gc_pauses_seconds_bucket', 'go_gc_pauses_seconds_count', 'go_gc_pauses_seconds_sum', 'go_gc_scan_globals_bytes', 'go_gc_scan_heap_bytes', 'go_gc_scan_stack_bytes', 'go_gc_scan_total_bytes', 'go_gc_stack_starting_size_bytes', 'go_godebug_non_default_behavior_allowmultiplevcs_events_total', 'go_godebug_non_default_behavior_asynctimerchan_events_total', 'go_godebug_non_default_behavior_containermaxprocs_events_total', 'go_godebug_non_default_behavior_embedfollowsymlinks_events_total', 'go_godebug_non_default_behavior_execerrdot_events_total', 'go_godebug_non_default_behavior_gocachehash_events_total', 'go_godebug_non_default_behavior_gocachetest_events_total', 'go_godebug_non_default_behavior_gocacheverify_events_total', 'go_godebug_non_default_behavior_gotestjsonbuildtext_events_total', 'go_godebug_non_default_behavior_gotypesalias_events_total', 'go_godebug_non_default_behavior_http2client_events_total', 'go_godebug_non_default_behavior_http2server_events_total', 'go_godebug_non_default_behavior_httpcookiemaxnum_events_total', 'go_godebug_non_default_behavior_httplaxcontentlength_events_total', 'go_godebug_non_default_behavior_httpmuxgo121_events_total', 'go_godebug_non_default_behavior_httpservecontentkeepheaders_events_total', 'go_godebug_non_default_behavior_installgoroot_events_total', 'go_godebug_non_default_behavior_multipartmaxheaders_events_total', 'go_godebug_non_default_behavior_multipartmaxparts_events_total', 'go_godebug_non_default_behavior_multipathtcp_events_total', 'go_godebug_non_default_behavior_netedns0_events_total', 'go_godebug_non_default_behavior_panicnil_events_total', 'go_godebug_non_default_behavior_randautoseed_events_total', 'go_godebug_non_default_behavior_randseednop_

In [ ]:
cpu_req_query       = 'sum(max by (cluster, namespace, pod, container)(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster="", node=~"(aj-aung-k8s-worker1|aj-aung-k8s-worker2)"})) by (pod)'
cpu_cap_query       = 'sum(kube_node_status_capacity{cluster="", job="kube-state-metrics", node=~"(aj-aung-k8s-worker1|aj-aung-k8s-worker2)", resource="cpu"})'
mem_req_query       = 'sum(max by (cluster, namespace, pod, container)(node_namespace_pod_container:container_memory_working_set_bytes{cluster="", node=~"(aj-aung-k8s-worker1|aj-aung-k8s-worker2)", container!=""})) by (pod)'
mem_cap_query       = 'sum(kube_node_status_capacity{cluster="", job="kube-state-metrics", node=~"(aj-aung-k8s-worker1|aj-aung-k8s-worker2)", resource="memory"})'
number_of_pod_query = 'sum(kube_pod_owner{job="kube-state-metrics", cluster="", node=~"(aj-aung-k8s-worker1|aj-aung-k8s-worker2)"}) by (namespace)'
number_of_pending_pod_query = 'sum(kube_pod_status_phase{job="kube-state-metrics", cluster="", node=~"(aj-aung-k8s-worker1|aj-aung-k8s-worker2)", phase="Pending"}) by (namespace)'

In [61]:
cpu_req_pd = MetricRangeDataFrame(prom.custom_query_range(query = cpu_req_query, start_time = start_time_thai, end_time = end_time_thai, step = "1m"))
cpu_cap_pd = MetricRangeDataFrame(prom.custom_query_range(query = cpu_cap_query, start_time = start_time_thai, end_time = end_time_thai, step = "1m"))
mem_req_pd = MetricRangeDataFrame(prom.custom_query_range(query = mem_req_query, start_time = start_time_thai, end_time = end_time_thai, step = "1m"))
mem_cap_pd = MetricRangeDataFrame(prom.custom_query_range(query = mem_cap_query, start_time = start_time_thai, end_time = end_time_thai, step = "1m"))
number_of_pod_pd = MetricRangeDataFrame(prom.custom_query_range(query = number_of_pod_query, start_time = start_time_thai, end_time = end_time_thai, step = "1m"))
number_of_pending_pod_query_pd = MetricRangeDataFrame(prom.custom_query_range(query = number_of_pending_pod_query, start_time = start_time_thai, end_time = end_time_thai, step = "1m"))

In [62]:
cpu_req_pd

                                                 pod  value
timestamp
2026-03-01 14:03:00                calico-node-22mlc   0.25
2026-03-01 14:04:00                calico-node-22mlc   0.25
2026-03-02 19:19:00                calico-node-44n6r   0.25
2026-03-02 19:20:00                calico-node-44n6r   0.25
2026-03-02 19:21:00                calico-node-44n6r   0.25
...                                              ...    ...
2026-03-01 09:03:00  cpu-stressor-ds-f5fc6fbc6-zzv9s   0.20
2026-03-01 09:04:00  cpu-stressor-ds-f5fc6fbc6-zzv9s   0.20
2026-03-01 09:05:00  cpu-stressor-ds-f5fc6fbc6-zzv9s   0.20
2026-03-01 09:06:00  cpu-stressor-ds-f5fc6fbc6-zzv9s   0.20
2026-03-01 09:07:00  cpu-stressor-ds-f5fc6fbc6-zzv9s   0.20

[93430 rows x 2 columns]

In [63]:
cpu_cap_pd

                     value
timestamp
2026-02-28 07:00:00    8.0
2026-02-28 07:01:00    8.0
2026-02-28 07:02:00    8.0
2026-02-28 07:03:00    8.0
2026-02-28 07:04:00    8.0
...                    ...
2026-03-03 06:56:00    8.0
2026-03-03 06:57:00    8.0
2026-03-03 06:58:00    8.0
2026-03-03 06:59:00    8.0
2026-03-03 07:00:00    8.0

[4321 rows x 1 columns]

In [64]:
mem_req_pd

                                                           pod        value
timestamp
2026-03-01 14:03:00                          calico-node-22mlc  136036352.0
2026-03-01 14:04:00                          calico-node-22mlc  139472896.0
2026-03-02 19:19:00                          calico-node-44n6r  146386944.0
2026-03-02 19:20:00                          calico-node-44n6r  146399232.0
2026-03-02 19:21:00                          calico-node-44n6r  146620416.0
...                                                        ...          ...
2026-03-03 00:31:00  prometheus-prometheus-node-exporter-znj47   20807680.0
2026-03-03 00:32:00  prometheus-prometheus-node-exporter-znj47   20602880.0
2026-03-03 00:33:00  prometheus-prometheus-node-exporter-znj47   20963328.0
2026-03-03 00:34:00  prometheus-prometheus-node-exporter-znj47   20430848.0
2026-03-03 06:24:00  prometheus-prometheus-node-exporter-zwznd    7880704.0

[133654 rows x 2 columns]

In [65]:
mem_cap_pd

                            value
timestamp
2026-02-28 07:00:00  1.281249e+10
2026-02-28 07:01:00  1.281249e+10
2026-02-28 07:02:00  1.281249e+10
2026-02-28 07:03:00  1.281249e+10
2026-02-28 07:04:00  1.281249e+10
...                           ...
2026-03-03 06:56:00  1.266779e+10
2026-03-03 06:57:00  1.266779e+10
2026-03-03 06:58:00  1.266779e+10
2026-03-03 06:59:00  1.266779e+10
2026-03-03 07:00:00  1.266779e+10

[4321 rows x 1 columns]

In [66]:
number_of_pod_pd

                      namespace  value
timestamp
2026-02-28 07:00:00     default   22.0
2026-02-28 07:01:00     default   24.0
2026-02-28 07:02:00     default   26.0
2026-02-28 07:03:00     default   27.0
2026-02-28 07:04:00     default   28.0
...                         ...    ...
2026-03-03 06:56:00  monitoring   29.0
2026-03-03 06:57:00  monitoring   29.0
2026-03-03 06:58:00  monitoring   29.0
2026-03-03 06:59:00  monitoring   29.0
2026-03-03 07:00:00  monitoring   29.0

[17284 rows x 2 columns]

In [67]:
number_of_pending_pod_query_pd

                      namespace  value
timestamp
2026-02-28 07:00:00     default    3.0
2026-02-28 07:01:00     default    0.0
2026-02-28 07:02:00     default    1.0
2026-02-28 07:03:00     default    0.0
2026-02-28 07:04:00     default    0.0
...                         ...    ...
2026-03-03 06:56:00  monitoring    0.0
2026-03-03 06:57:00  monitoring    0.0
2026-03-03 06:58:00  monitoring    0.0
2026-03-03 06:59:00  monitoring    0.0
2026-03-03 07:00:00  monitoring    0.0

[17284 rows x 2 columns]